name: Trigger Docs Deploy
on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy in target repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
            https://api.github.com/repos/b865-computer/b865-computer.github.io/dispatches \
            -d '{"event_type":"deploy_docs"}'
